### PR TITLE
che #18463 Adding clarification that Hosted Che is Eclipse Che hosted by Red Hat

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue https://github.com/eclipse/che/issues/18463

Try it on Hosted Che
[Contribute](https://che.openshift.io/f?url=https://github.com/ibuziuk/che-website)

image

image

### CODE REVIEW

**Comment by benoitf** [comment]
I think there is overlap with https://github.com/eclipse/che-website/pull/47

**Comment by ibuziuk** [comment]
@benoitf heh, so how would you like to proceed ;-) ?

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@ibuziuk let's merge yours first

**Comment by sunix** [comment]
hey, maybe we should also update these part: 
image

**Pull request merged**
