### PR TITLE
fix: removed eclipse theia

### PR DESCRIPTION
**Pull request by deerskindoll**
removed references to eclipse theia

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@deerskindoll tested on https://workspaces.openshift.com#https://github.com/eclipse-che/che-website/pull/102 and we need to align images properly

Screenshot 2024-05-15 at 18 29 55

**Comment by deerskindoll** [comment]
@ibuziuk the text is aligned now. please have a look: 
image

**Review by l0rd — APPROVED** [review]
LGTM

**Review by ibuziuk — APPROVED** [review]
great job

**Pull request merged**
